name: Django CI Pipeline
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Build Docker image
        run: |
          docker build -t tasksphere-django-app .
          
      - name: Run migrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          docker run --rm tasksphere-django-app python manage.py migrate
 
      - name: Run tests inside container
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          docker run --rm tasksphere-django-app python manage.py test
